name: Update RSS Feed

on:
  schedule:
    # Run once per day at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon python-dotenv
        
    - name: Create RSS feed
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      run: |
        python rss_telegram.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rss_feed.json
        git diff --staged --quiet || git commit -m "Auto-update JSON feed $(date)"
        git push
